# Generated by Django 5.0.6 on 2024-11-26 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_userinfo_id_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='numbers',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
